export const CLOUD = 'cloud'
export const CLOUDY = 'cloudy'
export const FOG = 'day-fog'
export const RAIN = 'rain'
export const SNOW = 'snow'
export const SUN = 'day-sunny'
export const WINDY = 'windy'
